/**
 * Generate blocks/manifest.json by walking the blocks/ tree.
 *
 * Convention:
 *   blocks/{category}/{PascalCase}/{PascalCase}.tsx
 *   blocks/{category}/{PascalCase}/block.config.json (optional metadata)
 *
 * Slug is derived from the PascalCase folder name: HeroPage → hero-page.
 * The renderer receives blockName "acf/hero-page" from WPGraphQL and resolves
 * it through this manifest to the right component path.
 *
 * Runs via `npm run manifests` (invoked automatically before dev/build).
 */

import { readdirSync, statSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

type BlockEntry = {
  slug: string;
  path: string;
  component: string;
  category: string;
  title: string;
  description: string;
  keywords: string[];
  requires: string[];
};

const BLOCKS_DIR = join(process.cwd(), "blocks");
const OUTPUT = join(BLOCKS_DIR, "manifest.json");
const IMPORTS_OUTPUT = join(process.cwd(), "lib/blocks/imports.ts");

const IGNORE = new Set(["node_modules", ".DS_Store"]);

const pascalToKebab = (name: string): string =>
  name
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();

const walkCategory = (category: string): BlockEntry[] => {
  const dir = join(BLOCKS_DIR, category);
  if (!existsSync(dir)) return [];

  return readdirSync(dir)
    .filter((name) => !IGNORE.has(name) && !name.startsWith("."))
    .map((name) => ({ name, full: join(dir, name) }))
    .filter(({ full }) => statSync(full).isDirectory())
    .map(({ name: componentName, full }): BlockEntry | null => {
      const tsx = join(full, `${componentName}.tsx`);
      if (!existsSync(tsx)) {
        console.warn(`[blocks] Skipping ${category}/${componentName} — no ${componentName}.tsx`);
        return null;
      }

      const configPath = join(full, "block.config.json");
      const config: Partial<Omit<BlockEntry, "slug" | "path" | "component" | "category">> =
        existsSync(configPath)
          ? JSON.parse(readFileSync(configPath, "utf8"))
          : {};

      const slug = pascalToKebab(componentName);

      return {
        slug,
        path: relative(BLOCKS_DIR, tsx),
        component: componentName,
        category,
        title: config.title ?? componentName,
        description: config.description ?? "",
        keywords: config.keywords ?? [],
        requires: config.requires ?? [],
      };
    })
    .filter((e): e is BlockEntry => e !== null);
};

const main = () => {
  if (!existsSync(BLOCKS_DIR)) {
    console.warn("[blocks] No blocks/ directory found, skipping manifest generation.");
    return;
  }

  const categories = readdirSync(BLOCKS_DIR)
    .filter((n) => !IGNORE.has(n) && !n.startsWith("."))
    .filter((n) => statSync(join(BLOCKS_DIR, n)).isDirectory());

  const blocks: Record<string, BlockEntry> = {};
  let count = 0;

  for (const category of categories) {
    for (const entry of walkCategory(category)) {
      if (blocks[entry.slug]) {
        console.warn(
          `[blocks] Duplicate slug "${entry.slug}" — ${blocks[entry.slug].category}/ vs ${entry.category}/`
        );
      }
      blocks[entry.slug] = entry;
      count++;
    }
  }

  const manifest = {
    generated: new Date().toISOString(),
    blocks,
  };

  writeFileSync(OUTPUT, JSON.stringify(manifest, null, 2) + "\n");
  console.log(`[blocks] Wrote ${count} block${count === 1 ? "" : "s"} to ${relative(process.cwd(), OUTPUT)}`);

  // Also generate a static imports map. Explicit imports (one per block) are
  // Turbopack-friendly — no template-literal globbing at build time.
  const entries = Object.values(blocks);
  const importsSrc = [
    "// AUTO-GENERATED by scripts/generate-blocks-manifest.ts — do not edit.",
    "// Static imports map so the block renderer never has to glob the filesystem.",
    "",
    "export const blockImports: Record<string, () => Promise<{ default: React.ComponentType<Record<string, unknown>> }>> = {",
    ...entries.map(
      (e) => `  "${e.slug}": () => import("@/blocks/${e.category}/${e.component}/${e.component}"),`
    ),
    "};",
    "",
  ].join("\n");
  writeFileSync(IMPORTS_OUTPUT, importsSrc);
  console.log(`[blocks] Wrote imports map to ${relative(process.cwd(), IMPORTS_OUTPUT)}`);
};

main();
