/**
 * Block Registry
 *
 * Reads blocks/manifest.json (generated by scripts/generate-blocks-manifest.ts)
 * and resolves a block slug to its component import path.
 *
 * Mirrors the DFREE_Block_Registry pattern in the sister PHP theme, minus the
 * transient cache — Node module caching handles that for us in one process.
 */

import type { BlocksManifest, BlockManifestEntry } from "./types";

let cached: BlocksManifest | null = null;

const loadManifest = async (): Promise<BlocksManifest> => {
  if (cached) return cached;
  try {
    const mod = await import("@/blocks/manifest.json");
    cached = (mod.default ?? mod) as BlocksManifest;
    return cached;
  } catch {
    return { generated: "", blocks: {} };
  }
};

/**
 * Look up a block's manifest entry by slug (e.g. "hero-page").
 */
export const getBlockEntry = async (slug: string): Promise<BlockManifestEntry | null> => {
  const manifest = await loadManifest();
  return manifest.blocks[slug] ?? null;
};

/**
 * Resolve `acf/hero-page` → "hero-page".
 * Non-ACF blocks (`core/paragraph` etc.) pass through unchanged; they won't
 * appear in the manifest and will render as a fallback.
 */
export const normalizeSlug = (blockName: string): string => blockName.replace(/^acf\//, "");
